#!/bin/sh

# SSH / GPG
unset SSH_AGENT_PID
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

gpgconf --launch gpg-agent

# Background
feh --bg-fill $HOME/pictures/wallpapers/journey-man.jpg

# BSPWM
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width       2
bspc config window_gap         12

bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true
