#!/bin/sh

#######
# Theme
#######

RED="#BF616A"
ORANGE="#D08770"
YELLOW="#EBCB8B"
GREEN="#A3BE8C"
PURPLE="#B48EAD"
BLUE="#5E81AC"
LIGHT="#D8DEE9"
DARK="#2E3440"

###########################
# Data generation functions
###########################

network() {
	ROUTE=$(ip route get 1.1.1.1 2> /dev/null)
       	RC=$?
	if [ $RC -ne 0 ]; then
		echo -n "Not Connected"
	else
		if [ "$(echo $ROUTE | grep -Po 'dev \K\w')" = "e" ]; then
	       		echo -n "Wired"
		else
			echo -n $(nmcli connection show | grep wifi | cut -d ' ' -f 1)
		fi
	fi
}

desktop() {
	INDEX=$(xprop -root _NET_CURRENT_DESKTOP | cut -d '=' -f 2)
	echo -n $(($INDEX + 1))
}

song() {
	echo -n $(mpc current)
}

clock() {
	echo -n $(date "+%a %b %d at %I:%M")
}

volume() {
	PARSE='
	/%/ {
		if ($7 == "off") { print "mute" }
		else { print $2"%" }
	}'
	echo -n $(amixer get Master | awk -F"[]%[]" "$PARSE")
}

battery() {
	VALUE=$(acpi --battery | cut -d, -f 2)
	echo -n ${VALUE%?}
}

######
# Main
######

# Format the lemonbar format string
format() {
	NETWORK_VALUE=$(network)
	if [ "$NETWORK_VALUE" = "Not Connected" ]; then
		NETWORK_COLOR=$RED
	else
		NETWORK_COLOR=$GREEN
	fi

	BATTERY_VALUE=$(battery)
	if [ "$BATTERY_VALUE" -lt "10" ]; then
		BATTERY_COLOR=$RED
	elif [ "$BATTERY_VALUE" -lt "25" ]; then
		BATTERY_COLOR=$YELLOW
	else
		BATTERY_COLOR=$BLUE
	fi

	echo -n "%{l}"
	echo -n "%{B$BLUE} Desktop $(desktop)  %{B-}"
	echo -n "%{B$GREEN} Volume $(volume)  %{B-}"
	
	SONG_VALUE=$(song)
	if [ "$SONG_VALUE" != "" ]; then
		echo -n "%{B$PURPLE}%{F$LIGHT} $SONG_VALUE %{F-}%{B-}"
	fi

	echo -n "%{c}"
	echo -n "$(clock)"
	echo -n "%{r}"
	echo -n "%{B$NETWORK_COLOR} $NETWORK_VALUE %{B-}"
	echo -n "%{B$BATTERY_COLOR} Battery $BATTERY_VALUE% %{B-}"
}

# Print the formatted string to stdout every second
while true; do
	echo $(format)
	sleep 1
done
